### ISSUE TITLE
Little advises

### ISSUE THREAD

**Issue by Kerollmops** [gnuvince/ppbert#1]
Here I'll just put some little advises.

In this function you:
- pass the ownership of the `Vec<u8>` to the function that is probably not needed, you could use a slice `&[u8]`, this follow the _minimum requirement_ rule.
- force an early return that is not needed, you could remove this `return` keyword.

https://github.com/gnuvince/ppbert/blob/5e32ad6fac9a54c77afd7133af493a1f25d5a703/src/main.rs#L165-L169

can be written as

```rust
fn parse_bert1(buf: &[u8]) -> Result<Vec<BertTerm>> { 
     let mut parser = parser::Parser::new(buf); 
     let term = parser.parse()?;
     Ok(vec![term])
} 
```

**Comment by gnuvince** [comment]
> pass the ownership of the Vec<u8> to the function that is probably not needed, you could use a slice &[u8], this follow the minimum requirement rule

I prefer to pass ownership of the buffer to the parser, especially since `main` won't do anything with it afterwards.

> force an early return that is not needed, you could remove this return keyword.

I like to use `return` when a function's body is imperative; I use return-by-expression only if the function is purely functional.
