### ISSUE TITLE
Could you tell me how I can read the ppbert output as json?

### ISSUE THREAD

**Issue by kyungtae** [gnuvince/ppbert#7]
It's great  that I can read the .bert2 data, but the JSON parser can't parse the output of ppbert.

**When I tried ppbert content.bert2, the output was like:**

{
  100,
  [
    {
      content,
      [
        {111, 50},
        {112, 50}
      ]
    }
  ]
}
{
  200,
  [
    {
      content,
      [
        {211, 100}
      ]
    }
  ]
}

**When I tried ppbert content.bert2 -j, the output was like:**

["100",[["content",[[111,50],[112,50]]]]
["200",[["content",[[211,100]]]]]

**Both was not the JSON format, what I expected was :**

{"100":[{"content":[{"111":50},{"112":50}]}]},
{"200":[{"content":[{"211":100}]}]}

**Isn't there a way to get proper JSON format output?**

**Comment by gnuvince** [comment]
You can try with `ppbert -jt` — the `-t` parameter will transform Erlang proplists into JSON objects, e.g.:

```
%% Erlang
[
  {foo, 42},
  {bar, 99}
]

%% ppbert -j
[
  ["foo", 42],
  ["bar", 99]
]

%% ppbert -jt
{
  "foo": 42,
  "bar": 99
}
```
